### ISSUE TITLE
Nim question

### ISSUE THREAD

**Issue by matkuki** [ventor3000/nimride#1]
Hi ventor3000,

I saw that you are the original author of the 'basic2d' library for the Nim programming language.
Can I ask you a couple of questions about the module?
Why does the Matrix2d have the tx and ty fields?
Is there a simple way to transpose a Matrix2d or is there a procedure that in not implemented for this?

Thanks,
Matic

**Comment by ventor3000** [comment]
Hi

The 2d matrix is modelled after a 3x3 matrix, in the same way as used in postscript and other common graphics packages:

ax bx 0
ay by 0
tx ty 1

tx,ty is the translate portion of the matrix, without it only scaling,shering and rotation could be described with it. Because the righmost column is always 0,0,1 in an affine 2d transformation, they are not stored in the matrix object. (In a 3d matrix, which would be 4x4, the rightmost column is needed for projection matrices)

**Comment by ventor3000** [comment]
There is no transpose for the 2d matrix. It is not possible because it does not store the rightmost column. The only use for transposing a 2d matrix that I can think of is to compute transformed normal vectors. However there is an optimized function for this in the basic2d module so you wont need to go the long route with transposing matrices.

**Comment by matkuki** [comment]
Thanks, looked into the basic2d module again and found that 'transformNorm' does the job.
I'm porting a 2D physics engine to Nim and it uses a transpose for the following(c++):
```c++
  // Transform circle center to Polygon model space
  Vec2 center = a->position; // 'a' is a circle shape class
  center = B->u.Transpose( ) * (center - b->position); 
  // 'B' is a polygon shape class and 'B->u' is the orientation matrix from model to world
```
Are you ever on the Nim IRC channel?

Thanks again,
Matic

**Comment by ventor3000** [comment]
No i've never been on on nimrod irc channel. Actually it was quite a while now since i used nimrod at all because of other projects that takes a lot of time. But i'll be back, be so sure. By the way let me know if transformNorm works as expected.
